### PR TITLE
remove unreachable code to avoid 'go vet' warnings

### PR DESCRIPTION
**Pull request by dmitris**
same as https://github.com/go-yaml/yaml/pull/173 with additional change in .travis.yaml to fix the build

### CODE REVIEW

**Comment by mogthesprog** [comment]
Is it possible to get this merged?

**Comment by niemeyer** [comment]
@mogthesprog Why do we need the additional go get call in travis?

**Comment by mogthesprog** [comment]
I hadn't noticed that. I'm pretty sure it's not needed at all. I can raise another PR without that change in it?

**Comment by niemeyer** [comment]
@mogthesprog Yes.. #173 was exactly that, but unfortunately it got removed after this PR.

Happy to merge if you can redo it.

**Comment by mogthesprog** [comment]
Sure, no worries. Bear with me a sec..

**Comment by niemeyer** [comment]
Sorted out in #249.

**Pull request closed without merging**
