### PR TITLE
Feature (v2): set the default line length to infinity (-1)

### PR DESCRIPTION
**Pull request by laverya**
as suggested here: https://github.com/go-yaml/yaml/issues/166#issuecomment-555447882

### CODE REVIEW

**Comment by jjshoe** [comment]
@niemeyer can we get this merged in?

**Comment by niemeyer** [comment]
Done!

**Comment by niemeyer** [comment]
@laverya Thanks for the PR.

**Comment by laverya** [comment]
Is there any chance of this becoming a release soon @niemeyer? Or do we need to wait longer to see if objections are raised?

**Comment by niemeyer** [comment]
Wish conceded!  I think we've waited enough.

I'm also thinking of tagging v3 in the next few days, and switching over to it as the main branch. Blockers are almost over.

**Pull request merged**
