### PR TITLE
chore(v2): cleanup go.mod and add go.sum

### PR DESCRIPTION
**Pull request by chenrui333**
relates to #510

### CODE REVIEW

**Comment by niemeyer** [comment]
I can't see a reason to hardcode the version of go-check. We want whatever is the latest version of v1 in our tests, not that specific digest.

**Comment by chenrui333** [comment]
@niemeyer I think the intention of `go.sum` is good for cross-module reference. The `go.mod` is just a result of `go mod tidy` though.

**Comment by janisz** [comment]
@niemeyer What's the status of this? Without `go.sum` @dependabot is not able to verify dependencies

> Dependabot can't resolve your Go dependency files Dependabot failed to update your dependencies because there was an error resolving your Go dependency files.
>
> Dependabot encountered the following error:
>
> verifying github.com/go-yaml/yaml/v2@v2.4.0/go.mod: checksum mismatch

**Comment by janisz** [comment]
Why this was closed?

**Pull request closed without merging**
