### PR TITLE
Don't ignore unspecified fields (from #136)

### PR DESCRIPTION
**Pull request by douglaswth**
This is based on @oec's comment in #136.

### CODE REVIEW

**Comment by dhiltonp** [comment]
+1

**Comment by jdonboch** [comment]
+1

**Review by jdonboch — APPROVED** [review]

**Comment by niemeyer** [comment]
We can't change the default behavior like this, but we can have a mode on a `Decoder` that enables it.

**Comment by gemcdaniel** [comment]
I would like to see a mode on a `Decode` for strict decoding that would be thread-safe.

**Comment by jdonboch** [comment]
@niemeyer We opened another PR #210 that doesn't change the default behavior and adds the concept of a moded Decoder

**Comment by niemeyer** [comment]
Sounds good, thanks for that.

My most pressing deadlines elsewhere are due this month, so you can expect some good amount of love in go-yaml soon.

**Pull request closed without merging**
