### PR TITLE
Rename LICENSE to NOTICE & Add Apache Text in LICENSE

### LINKED ISSUE #235: please use official Apache 2.0 license text in LICENSE for tools to identify
Our project has 30 or so dependencies, one being go-yaml/yaml.
We use tools to help identify the licenses of our dependencies, and ensure we provide proper copyright attributions to the authors, like you.

Our tools could not identify this project's license.

Most Apache projects use the [official Apache 2.0 license text](http://www.apache.org/licenses/LICENSE-2.0.txt) verbatim in `LICENSE`, and put copyright attributions (which you currently have in your `LICENSE` file) in a `NOTICE` file.

Can you please rename your `LICENSE` file to `NOTICE` and add the official Apache 2.0 license text as `LICENSE` into your project?

That should help our tools, as well as [GitHub's console to display your license on the repo overview](https://github.com/blog/2252-license-now-displayed-on-repository-overview).
That would also ensure, by way of section 4(d) of the Apache 2.0 license, that projects using your project credit you for your work.

### PR DESCRIPTION
**Pull request by king-jam**
This resolves https://github.com/go-yaml/yaml/issues/235

### CODE REVIEW

**Comment by niemeyer** [comment]
LGTM, but I don't think we need the NOTICE file if we're adding the license explicitly.

**Comment by king-jam** [comment]
@niemeyer updated per your note. Was being very detailed. 😃 Should be good to merge now then.

**Comment by niemeyer** [comment]
Thanks!

**Comment by dkoper** [comment]
@niemeyer This has removed the (Canonical) copyright statement - it's not anywhere anymore. The Apache license refers to the Copyright owner in its conditions, but it's now hard to track who the copyright owners are.
In the Apache foundation, it's common to include a NOTICE file with the copyright attribution.

It would be great for users of your library, like me, if you could restore the original Canonical copyright statement into a NOTICE file.
In fact, it would be even better if you could rename `LICENSE.libyaml` to `NOTICE` and add a copyright statement at the top, followed by the list of libyaml exceptions.

I can submit a PR for this if you like.

**Comment by king-jam** [comment]
@dkoper the original NOTICE file was intended to resolve the issue you have. Tagging it back in should be very easy. I think the LICENSE.libyaml has to stay legally....I am probably wrong as an armchair licensing lawyer though.

**Comment by dkoper** [comment]
Tagging back would be great! Please let me know if you need me to submit a PR or issue to track it.

Let me submit a separate issue on the LICENSE.libyaml - it's not really related as you point out.

**Comment by king-jam** [comment]
Added: https://github.com/go-yaml/yaml/pull/292

**Pull request merged**
