### PR TITLE
Correctly quote date-like strings

### LINKED ISSUE #192: Marshaler incorrectly marshals date strings
The marshaler should quote strings that have YAML's date format. For example, the go string "2006-01-02T15:04:05Z" should be marshaled as '2006-01-02T15:04:05Z', with the quotes, but is currently marshaled without quotes.

SSCCE:

```
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
)

func main() {
    m := make(map[string]string)
    m["foo"] = "2006-01-02T15:04:05Z"
    out, _ := yaml.Marshal(m)
    fmt.Println(string(out))
}
```

Should output:

`foo: '2006-01-02T15:04:05Z'`

But instead outputs

`foo: 2006-01-02T15:04:05Z`

### PR DESCRIPTION
**Pull request by autrilla**
Fixes #192 

(this is a copy of #193, but since then, we've needed to move the fix to another branch)

### CODE REVIEW

**Comment by autrilla** [comment]
I'm not sure why this is broken on tip

**Comment by vinzenz** [comment]
@autrilla It's fixed by #217 - It's a change in the time stdlib

**Comment by rogpeppe** [comment]
Fixed by #310.

**Comment by autrilla** [comment]
@rogpeppe I'm not sure this is fixed, unless I'm misunderstanding things. Running the reproduction case from the issue:

```
cd /tmp && mkdir gotmp && export GOPATH=/tmp/gotmp && go get -u gopkg.in/yaml.v2 && cat <<EOF > main.go && go run main.go
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
)

func main() {
    m := make(map[string]string)
    m["foo"] = "2006-01-02T15:04:05Z"
    out, _ := yaml.Marshal(m)
    fmt.Println(string(out))
}
EOF
```

Outputs:

```
foo: 2006-01-02T15:04:05Z
```

But if it was fixed, it should have output the date string quoted with single or double quotes.

Edit: Oh, never mind, I see this is on the `devel` branch.

**Pull request closed without merging**
