### PR TITLE
Stream Encoder/Decoder like json/xml

### PR DESCRIPTION
**Pull request by im-kulikov**
* workaround implementation of Encoder/Decoder
* merging with master branch
* typos
* formatting
* fixes for linter-warnings
* fixes for tests

### CODE REVIEW

**Comment by im-kulikov** [comment]
I have some troubles with writing test cases for NewEncoder.. mb few days and I commit changes

**Comment by im-kulikov** [comment]
ping @niemeyer, @rogpeppe

**Comment by im-kulikov** [comment]
@niemeyer, @rogpeppe is there changes, what I can do for approve?

**Comment by im-kulikov** [comment]
ping @niemeyer, @rogpeppe?

**Comment by im-kulikov** [comment]
one gets the impression that the project is dead...

**Comment by im-kulikov** [comment]
@rogpeppe ping? it makes sense to continue?

**Comment by im-kulikov** [comment]
conflicts resolved

**Comment by rogpeppe** [comment]
This seems like there's much more than a stream encoder being proposed.
While I don't necessarily disagree with many of the changes, they don't seem to
fit with the PR title and should probably be proposed separately.

**Comment by im-kulikov** [comment]
@rogpeppe what changes you would like to separate?
- dep 
- fixes for testing
- refactoring

**Comment by im-kulikov** [comment]
I can revert dep..
Stream encode/decode depends on refactoring and test fixes

**Comment by rogpeppe** [comment]
Thanks, but this has been superceded by #301 and #306.

**Pull request closed without merging**
