### PR TITLE
custom tags support

### PR DESCRIPTION
**Pull request by jdamick**
i'd like to be able handle custom yaml tags; similar support is found in other language yaml implementations.  So this changes adds support to register a tag unmarshaler.  Please let me know if this is something you'd like to handle a different way & i'd be happy to modify it.

### CODE REVIEW

**Comment by technosophos** [comment]
I'd like this feature as well.

**Comment by tomnz** [comment]
We're trying to support custom parsing into decimals with go-yaml. Currently we have to special case it (look for a particular structure e.g. `{ decimal: "0.123" }` in the YML), but it would be much cleaner to parse it as `!dec "0.123"` instead. Looks like this diff would work great! It's a shame we can't use custom YAML tags currently.

**Comment by jdamick** [comment]
@niemeyer any chance we can get this feature added?

**Comment by rogpeppe** [comment]
I'm not convinced that custom tag unmarshalers should be globally registered. Also, this only covers tagged strings, not tagged sequences or mappings.

**Comment by lox** [comment]
Completely agree @rogpeppe, seems like this will probably be superseded by https://github.com/go-yaml/yaml/pull/332

**Comment by niemeyer** [comment]
This will be doable in v3 by unmarshalling into the intermediate representation and then using it to decode as desired.

**Pull request closed without merging**
