### PR TITLE
Added ability to customize default map type

### PR DESCRIPTION
**Pull request by algobardo**
Would allow me to cope with #384

### CODE REVIEW

**Comment by steve-gray** [comment]
+1 on this. The inability to do this breaks a *lot* of code that works on maps, and requires a lot of fairly evil hacking to work around (recursive replacement of maps)

**Comment by mikefarah** [comment]
Nice - do you mind giving a little snippet of how this change could be used to change the default map type?

**Comment by virtuald** [comment]
Something like

```
decoder := NewDecoder()
decoder.SetDefaultMapType(reflect.TypeOf(map[string]interface{}{}))
err := decoder.Unmarshal(whatever, thing)
```

**Comment by dlahoza** [comment]
+1 from me

**Comment by niemeyer** [comment]
I've been working on v3, and will consider the underlying problem here before releasing to make sure it is addressed. Without a new version where we can break compatibility in edge cases, I think we may be able to address this issue without an explicit function call like this, by recording the generic map the decoder last went through. I've done the same in a different marshaling package and it worked well. I'll update this issue once v3 is ready for testing.

**Comment by niemeyer** [comment]
Okay, in v3 decoding a map into an interface{} when it has _only_ string keys will decode as map[string]interface{}, and not map[interface{}]interface{}. If there are non-string keys, the latter will be used to ensure the values can roundtrip.

I'm hoping this will properly address the mentioned cases without breaking usability for general yaml maps. I will close this pull request now, and will close the related issue once v3 is generally available.

**Comment by ktogo** [comment]
@niemeyer In the meantime I would still love this solution to be merged, so that we can move forward for now.

Also even on v3 we’ll be able to lock the type into `map[string]interface{}` where we don’t expect other type as map keys with this default type hinting solution.
(In that case developers need to implement the type casting/validating code at everywhere they need string type keys without it)

**Comment by marwatk** [comment]
@niemeyer Would it be possible to reexamine this MR? It's pretty minor and it's been a year since the closure and v2 is still the default branch. A lot of projects are using a fork to accomplish it, but we'd rather not have to.

**Pull request closed without merging**
