### PR TITLE
Add method to set preferred line width.

### LINKED ISSUE #166: Marshalling long, single-line strings results in (correct) line breaks
When long, single-line strings (i.e. does not contain "\n") are marshalled, the yaml emitter seems to force line breaks at 80 characters, but does so without prefixing the string with the multi-line notation (e.g. ">" or "|"). This results in unusable yaml output like in the example below.

**Example:**

``` go
data := yaml.MapSlice{{"test", "abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd"}}

res, _ := yaml.Marshal(data)
fmt.Println(string(res))
```

**Output:**

``` yaml
test: abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd
  abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd
```

As a workaround, simply appending "\n" to the end of a string that's known to be lengthy works fine, although not ideal since the yaml output now exceeds the 80 char width. Mutiline ">" prefixed outputs would be preferable.

**Output with trailing \n:**

``` yaml
test: |
  abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd aabdasfadsfdasfadsfasd abdasfadsfdasfadsfasd abdasfadsfdasfadsfasd
```

Appreciate if someone could confirm whether this is an issue or just incorrect usage. If a fix is needed, I'd be happy to work on a PR. Thanks!

### PR DESCRIPTION
**Pull request by alexandrevicenzi**
This should fix #166, let me know if I need to change something.

### CODE REVIEW

**Comment by lox** [comment]
Would it be possible to add a test for this @alexandrevicenzi?

**Comment by alexandrevicenzi** [comment]
I'll take a look.

**Comment by niemeyer** [comment]
v3 is coming and we'll use a different style to provide such options. Please feel free to resubmit once it's out.

**Comment by sagikazarmark** [comment]
Is v3 still coming? This seems to be a minor change for a rather serious issue for quite a lot of people, so it would be nice to have this before v3 if it takes another year to reach stable.

**Comment by niemeyer** [comment]
Yep, it's coming.

**Pull request closed without merging**
