### PR TITLE
Add a function to disable unique keys

### LINKED ISSUE #751: v3: feature request: yaml should provide function to disable unique keys.
### Why we need this feature?
The `strict` flag was split into `knownFields` and `uniqueKeys` in commit 085f3822ccabf97875c60131b52575a980b634a8. 
But in commit 309c9d15755818936fcb0f5c171692693a47efe2,`uniqueKeys` was dropped and set to true.
If yaml text has duplicate keys, `Decoder.Decode` and `yaml.Unmarshal` will return errors. This result in application likes kustomize returns errors after version v3.9.0, since kustomize uses  `yaml.Unmarshal` of v3. 
I think it is a good option to provide a function to disable unique keys, then these application could ignore duplicate keys.

### Related issues
https://github.com/kubernetes-sigs/kustomize/issues/3480
https://github.com/kubesphere/kubesphere/issues/3933

### PR DESCRIPTION
**Pull request by xyz-li**
Provide function `DisableUniqueKeys` to disable unique keys option.

Fixes #751

### CODE REVIEW

**Comment by xyz-li** [comment]
@niemeyer

**Comment by manu11th** [comment]
Are there any news on this?

**Comment by davisford** [comment]
Is it possible for the maintainers to get a review on this?  This is a serious problem for us.  I have left my comment [here](https://github.com/go-yaml/yaml/issues/751#issuecomment-961289454) describing why.

**Pull request closed without merging**
