### PR TITLE
Fix broken inheritance when using yaml.MapSlice (Was #91 and #184)

### PR DESCRIPTION
**Pull request by vinzenz**
This should fix the broken inheritance when using yaml.MapSlice

### CODE REVIEW

**Comment by donny-dont** [comment]
@niemeyer any chance you could give this a review? It getting merged will save us a goofy workaround in Drone.

**Comment by bradrydzewski** [comment]
@vinzenz I confirmed this PR fixes issue #184 as well. Thanks!

**Comment by macrael** [comment]
Why hasn't this fix been merged?

**Comment by macrael** [comment]
This appears to still be broken on ToT

**Comment by lox** [comment]
Just ran into this too, is there any way we can assist with getting this reviewed and merged @niemeyer?

**Comment by niemeyer** [comment]
Sorry for the lack of feedback here. I can't just merge this PR as there are a number of unrelated changes in it. That said, MapSlice is about to die. yaml.v3 is on the way and a much more comprehensive way to decode content partially and preserve style will be introduced.

**Comment by lox** [comment]
@vinzenz any chance you could put in a new pull request that is just the tests and fix for the issue with anchors/merge as raised in https://github.com/go-yaml/yaml/issues/184?

**Pull request closed without merging**
