### PR TITLE
Cannot marshal/unmarshal time.Time

### PR DESCRIPTION
**Pull request by ewalk153**
This only answers half the problem: encoding. Test included as well.

### CODE REVIEW

**Comment by niemeyer** [comment]
I'm happy to merge this. Can you please sign the contribution agreement:

```
http://www.canonical.com/contributor-license-agreement
```

It's a straightforward/non-draconian one.

**Comment by ewalk153** [comment]
It should be properly filled out.

**Comment by niemeyer** [comment]
Thanks!  Can you include the decoding side, now that the non-pointer bug is fixed?

**Comment by ewalk153** [comment]
Yeah, I'll take another look.

**Comment by niemeyer** [comment]
Ah, we have to look at something else too. The time.Time encoding and decoding format must match the standard yaml timestamp type: http://yaml.org/type/timestamp.html

**Comment by ewalk153** [comment]
Fixing the formatting should be quick here.

The decoding looks to be a little more complicated. I'm not sure how to infer the type of the target field. Any suggestions?

**Comment by niemeyer** [comment]
We can just try them all in sequence, starting by the format we marshal out so that the default encode/decode sequence hits on the first try.

**Comment by ewalk153** [comment]
I'm getting stuck using reflection to assign the out value.

As a `time.Time` struct has only exported fields, I'm not sure out to assign to it.

http://play.golang.org/p/Z-pI2fm_Fa

**Comment by niemeyer** [comment]
We need time handling, but we need both sides of it. I'm closing this for lack of activity. Please feel free to push the complete change once you're ready.

**Pull request closed without merging**
