### PR TITLE
Fix for issue #157 - go-yaml should handle invalid integers as strings

### PR DESCRIPTION
**Pull request by vinzenz**

### CODE REVIEW

**Comment by niemeyer** [comment]
It's not clear to me how this is fixing the referenced issue in a proper way. What's the actual specification of the float format in yaml, and how is this handling it? Where are the tests for it showing details of the problem being fixed?

**Comment by vinzenz** [comment]
> It's not clear to me how this is fixing the referenced issue in a proper way. 

ParseFloat is  behaving oddly by discarding the leading 0 and make the rest of the number a float.

> What's the actual specification of the float format in yaml, and how is this handling it? 

http://yaml.org/spec/1.2/spec.html#tag/repository/float
A leading 0 is only allowed when followed by a dot, which it checks for and then passes the string on to really try a float. (tryFloat)

> Where are the tests for it showing details of the problem being fixed?

I will add some test that would fail before

**Comment by niemeyer** [comment]
Note that this changed from yaml 1.1 to 1.2. It might be okay, but we may also end up breaking existing code. In Python:
```
>>> import yaml
>>> yaml.load("01.1")
1.1
```
Thanks for the tests.

**Comment by niemeyer** [comment]
Curiously, Python float resolution seems broken in other ways:
```
>>> yaml.load("-2E+05")
'-2E+05'
```

**Comment by vinzenz** [comment]
#171  seems to actually fix this already

**Comment by vinzenz** [comment]
And we can also add this as a parser option (Strict floats) like it was introduced as another PR

**Comment by niemeyer** [comment]
Indeed, merged #171. Thanks for your help on this.

**Pull request closed without merging**
